### ISSUE TITLE
Release 1.2?

### ISSUE THREAD

**Issue by semcha** [markporoshin/dbt-greenplum#10]
@markporoshin
What needs to be done for release 1.2?

**Comment by markporoshin** [comment]
Hello, I'm going to do it soon =) I'm in vacation at the moment

**Comment by semcha** [comment]
Thank you! I'm ready to help if you need

**Comment by markporoshin** [comment]
@semcha Hi! As I can see, I can just update the version and it will work)
It will be fine if you join us to improve the adapter together. I'm considering testing, but don't know how to implement it at the moment

I've uploaded a new version of adapter to pypi

P.S. I'm working on dbtvault for Greenplum now. Probably it will be useful to you
